# https://circleci.com/docs/sample-config/
jobs:
  build:
    steps:
      - checkout
      # ruleid: command-parameter-interpolation
      - run: "echo << parameters.input >> "

  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
      - run:
          name: Clone
          # ruleid: command-parameter-interpolation
          command: git clone << pipeline.parameters.src-repo-url >> -b <<pipeline.parameters.branch-name >>

      - run:
          environment:
            REPO_URL: << pipeline.parameters.src-repo-url >>
            BRANCH: << pipeline.parameters.branch-name >>
            # ok: command-parameter-interpolation
            command: << pipeline.parameters.branch-name >>
          # ok: command-parameter-interpolation
          command: git clone "$REPO_URL" -b "$BRANCH"
